package autoandshare.headvr.lib;

public enum Actions {
    NoAction,
    PartialAction,
    PlayOrPause,
    NextFile,
    PrevFile,
    BeginSeek,
    ContinueSeek,
    CancelSeek,
    ConfirmSeek,
    IncreaseEyeDistance,
    DecreaseEyeDistance,
    Force2D,
    Recenter,
    Back,
    IncreaseScreenSize,
    DecreaseScreenSize,
    MoveScreenUp,
    MoveScreenDown,
    IncreaseVolume,
    DecreaseVolume,
    SingleSeek,
}
